import math
from typing import List, Dict, Any, Optional, Tuple
from datetime import datetime, timezone
from app.schemas.thermal import IndustrialFacility

class AttributionService:
    def __init__(self):
        self.facilities: Dict[str, IndustrialFacility] = {}
        self._seed_authoritative_facilities()

    def _seed_authoritative_facilities(self):
        """
        Seeds authoritative industrial facility GIS footprints based on OSM, Global Energy Monitor (GEM),
        and Bhuvan industrial registries across key Indian economic corridors.
        """
        seeds = [
            IndustrialFacility(
                id="FAC-DAHEJ-PCH01",
                name="PetroChem Complex Alpha - Unit 04",
                sector="PETROCHEMICAL",
                state="Gujarat",
                district="Bharuch",
                cluster_name="Dahej PCPIR Special Economic Zone",
                coordinates=[21.6850, 72.5750],
                fence_radius_m=1200.0,
                operator_name="Bharat Petrochemical Industrial Corp.",
                erdmp_license="PESO/IND/2024/GJ-DAHEJ-1505",
                major_chemicals_stored=["Ammonia (Anhydrous)", "Benzene (Pure Grade)", "Liquefied Petroleum Gas", "Chlorine"],
                known_flares_count=3,
                known_furnaces_count=2,
                baseline_mean_frp_mw=18.5,
                baseline_std_frp_mw=4.2,
                baseline_mean_temp_k=348.0,
                expected_diurnal_ratio=0.98,
                historical_detections_count=186,
                active_hotspots_count=1,
                current_max_frp_mw=19.2,
                current_abnormality_score=12.0,
                current_status="NOMINAL_OPERATIONS",
                last_satellite_overpass=datetime.now(timezone.utc)
            ),
            IndustrialFacility(
                id="FAC-DAHEJ-LNG02",
                name="Petronet Dahej LNG Cryogenic Regasification Terminal",
                sector="REFINERY",
                state="Gujarat",
                district="Bharuch",
                cluster_name="Dahej Port & PCPIR Corridor",
                coordinates=[21.6720, 72.5320],
                fence_radius_m=1500.0,
                operator_name="Petronet LNG Limited",
                erdmp_license="PESO/IND/2023/GJ-LNG-0042",
                major_chemicals_stored=["Liquefied Natural Gas", "Boil-off Gas (Methane)"],
                known_flares_count=2,
                known_furnaces_count=0,
                baseline_mean_frp_mw=24.0,
                baseline_std_frp_mw=5.5,
                baseline_mean_temp_k=352.0,
                expected_diurnal_ratio=1.02,
                historical_detections_count=240,
                active_hotspots_count=1,
                current_max_frp_mw=25.4,
                current_abnormality_score=8.5,
                current_status="NOMINAL_OPERATIONS",
                last_satellite_overpass=datetime.now(timezone.utc)
            ),
            IndustrialFacility(
                id="FAC-JAMNAGAR-REF01",
                name="Reliance Jamnagar Mega Refinery & Petrochemical Complex",
                sector="REFINERY",
                state="Gujarat",
                district="Jamnagar",
                cluster_name="Jamnagar Energy Superhub",
                coordinates=[22.3600, 69.8300],
                fence_radius_m=4500.0,
                operator_name="Reliance Industries Limited",
                erdmp_license="PESO/IND/2024/GJ-JAM-0001",
                major_chemicals_stored=["Crude Oil", "Naphtha", "Propylene", "Ethylene", "LPG"],
                known_flares_count=14,
                known_furnaces_count=18,
                baseline_mean_frp_mw=145.0,
                baseline_std_frp_mw=22.0,
                baseline_mean_temp_k=375.0,
                expected_diurnal_ratio=0.99,
                historical_detections_count=1840,
                active_hotspots_count=4,
                current_max_frp_mw=152.0,
                current_abnormality_score=15.0,
                current_status="NOMINAL_OPERATIONS",
                last_satellite_overpass=datetime.now(timezone.utc)
            ),
            IndustrialFacility(
                id="FAC-HAZIRA-GAS01",
                name="ONGC Hazira Gas Processing & Petrochemical Complex",
                sector="PETROCHEMICAL",
                state="Gujarat",
                district="Surat",
                cluster_name="Hazira Industrial Belt",
                coordinates=[21.1200, 72.6700],
                fence_radius_m=2000.0,
                operator_name="Oil and Natural Gas Corporation",
                erdmp_license="PESO/IND/2022/GJ-HAZ-0089",
                major_chemicals_stored=["Sour Gas", "LPG", "Sulfur", "Condensate"],
                known_flares_count=5,
                known_furnaces_count=4,
                baseline_mean_frp_mw=38.0,
                baseline_std_frp_mw=8.0,
                baseline_mean_temp_k=360.0,
                expected_diurnal_ratio=0.96,
                historical_detections_count=620,
                active_hotspots_count=2,
                current_max_frp_mw=41.2,
                current_abnormality_score=14.0,
                current_status="NOMINAL_OPERATIONS",
                last_satellite_overpass=datetime.now(timezone.utc)
            ),
            IndustrialFacility(
                id="FAC-VADODARA-REF01",
                name="IOCL Gujarat Refinery & Petrochemical Complex",
                sector="REFINERY",
                state="Gujarat",
                district="Vadodara",
                cluster_name="Koyali Petrochemical Hub",
                coordinates=[22.3550, 73.1350],
                fence_radius_m=2800.0,
                operator_name="Indian Oil Corporation Limited",
                erdmp_license="PESO/IND/2024/GJ-VAD-0012",
                major_chemicals_stored=["Aviation Turbine Fuel", "Naphtha", "Diesel", "Benzene"],
                known_flares_count=4,
                known_furnaces_count=8,
                baseline_mean_frp_mw=42.0,
                baseline_std_frp_mw=6.5,
                baseline_mean_temp_k=358.0,
                expected_diurnal_ratio=0.97,
                historical_detections_count=710,
                active_hotspots_count=2,
                current_max_frp_mw=44.8,
                current_abnormality_score=9.2,
                current_status="NOMINAL_OPERATIONS",
                last_satellite_overpass=datetime.now(timezone.utc)
            ),
            IndustrialFacility(
                id="FAC-MUMBAI-REF01",
                name="Mumbai Chembur Coastal Petrochemicals & Refinery",
                sector="REFINERY",
                state="Maharashtra",
                district="Mumbai Suburban",
                cluster_name="Mahul / Chembur Coastal Hub",
                coordinates=[19.0050, 72.8950],
                fence_radius_m=2400.0,
                operator_name="Bharat Petroleum / HPCL",
                erdmp_license="PESO/IND/2023/MH-MUM-0004",
                major_chemicals_stored=["Motor Spirit", "High Speed Diesel", "LPG", "Fuel Oil"],
                known_flares_count=6,
                known_furnaces_count=10,
                baseline_mean_frp_mw=58.0,
                baseline_std_frp_mw=11.0,
                baseline_mean_temp_k=362.0,
                expected_diurnal_ratio=0.99,
                historical_detections_count=1120,
                active_hotspots_count=2,
                current_max_frp_mw=61.5,
                current_abnormality_score=11.5,
                current_status="NOMINAL_OPERATIONS",
                last_satellite_overpass=datetime.now(timezone.utc)
            ),
            IndustrialFacility(
                id="FAC-ROURKELA-STEEL01",
                name="Rourkela Integrated Steel Plant",
                sector="STEEL",
                state="Odisha",
                district="Sundargarh",
                cluster_name="Rourkela Metallurgical Corridor",
                coordinates=[22.2150, 84.8650],
                fence_radius_m=3200.0,
                operator_name="Steel Authority of India Limited",
                erdmp_license="PESO/IND/2022/OR-ROU-0018",
                major_chemicals_stored=["Liquid Steel", "Coke Oven Gas", "Blast Furnace Slag"],
                known_flares_count=2,
                known_furnaces_count=8,
                baseline_mean_frp_mw=72.0,
                baseline_std_frp_mw=14.0,
                baseline_mean_temp_k=372.0,
                expected_diurnal_ratio=0.95,
                historical_detections_count=890,
                active_hotspots_count=2,
                current_max_frp_mw=76.0,
                current_abnormality_score=13.0,
                current_status="NOMINAL_OPERATIONS",
                last_satellite_overpass=datetime.now(timezone.utc)
            ),
            IndustrialFacility(
                id="FAC-PARADIP-PETRO01",
                name="Indian Oil Paradip Refinery & Petrochemical Complex",
                sector="PETROCHEMICAL",
                state="Odisha",
                district="Jagatsinghpur",
                cluster_name="Paradip PCPIR Deepwater Hub",
                coordinates=[20.2854, 86.6432],
                fence_radius_m=3500.0,
                operator_name="Indian Oil Corporation Limited",
                erdmp_license="PESO/IND/2024/OR-PAR-0002",
                major_chemicals_stored=["Polypropylene", "Ethylene Glycol", "Naphtha", "LPG"],
                known_flares_count=5,
                known_furnaces_count=12,
                baseline_mean_frp_mw=95.0,
                baseline_std_frp_mw=18.0,
                baseline_mean_temp_k=368.0,
                expected_diurnal_ratio=0.98,
                historical_detections_count=1430,
                active_hotspots_count=3,
                current_max_frp_mw=102.0,
                current_abnormality_score=14.2,
                current_status="NOMINAL_OPERATIONS",
                last_satellite_overpass=datetime.now(timezone.utc)
            ),
            IndustrialFacility(
                id="FAC-KORBA-PWR01",
                name="NTPC Korba Super Thermal Power Station (2600 MW)",
                sector="THERMAL_POWER",
                state="Chhattisgarh",
                district="Korba",
                cluster_name="Korba Coal & Power Basin",
                coordinates=[22.3800, 82.6800],
                fence_radius_m=3000.0,
                operator_name="NTPC Limited",
                erdmp_license="CEA/IND/2023/CG-KORBA-01",
                major_chemicals_stored=["Bituminous Coal", "Furnace Heavy Oil", "Fly Ash"],
                known_flares_count=0,
                known_furnaces_count=7,
                baseline_mean_frp_mw=65.0,
                baseline_std_frp_mw=12.0,
                baseline_mean_temp_k=365.0,
                expected_diurnal_ratio=0.94,
                historical_detections_count=980,
                active_hotspots_count=3,
                current_max_frp_mw=70.5,
                current_abnormality_score=18.0,
                current_status="NOMINAL_OPERATIONS",
                last_satellite_overpass=datetime.now(timezone.utc)
            ),
            IndustrialFacility(
                id="FAC-JSR-STEEL01",
                name="Tata Steel Jamshedpur Integrated Steel Works",
                sector="STEEL",
                state="Jharkhand",
                district="East Singhbhum",
                cluster_name="Jamshedpur Metallurgical Cluster",
                coordinates=[22.7800, 86.2000],
                fence_radius_m=3500.0,
                operator_name="Tata Steel Limited",
                erdmp_license="PESO/IND/2021/JH-JSR-0012",
                major_chemicals_stored=["Coke Oven Gas", "Blast Furnace Slag", "Liquid Iron", "Oxygen"],
                known_flares_count=4,
                known_furnaces_count=6,
                baseline_mean_frp_mw=82.0,
                baseline_std_frp_mw=16.0,
                baseline_mean_temp_k=380.0,
                expected_diurnal_ratio=0.97,
                historical_detections_count=1250,
                active_hotspots_count=3,
                current_max_frp_mw=88.0,
                current_abnormality_score=16.5,
                current_status="NOMINAL_OPERATIONS",
                last_satellite_overpass=datetime.now(timezone.utc)
            ),
            IndustrialFacility(
                id="FAC-JHARIA-MINE01",
                name="BCCL Jharia Opencast Coal Mining & Seam Fire Sector",
                sector="MINING",
                state="Jharkhand",
                district="Dhanbad",
                cluster_name="Jharia Coalfield Mining Zone",
                coordinates=[23.7500, 86.4200],
                fence_radius_m=5000.0,
                operator_name="Bharat Coking Coal Limited",
                erdmp_license="DGMS/IND/2020/JH-JHA-MINE",
                major_chemicals_stored=["Coking Coal", "Explosives ANFO", "Subsurface Methane"],
                known_flares_count=0,
                known_furnaces_count=0,
                baseline_mean_frp_mw=110.0,
                baseline_std_frp_mw=28.0,
                baseline_mean_temp_k=395.0,
                expected_diurnal_ratio=0.91,
                historical_detections_count=2100,
                active_hotspots_count=5,
                current_max_frp_mw=118.0,
                current_abnormality_score=22.0,
                current_status="NOMINAL_OPERATIONS",
                last_satellite_overpass=datetime.now(timezone.utc)
            ),
            IndustrialFacility(
                id="FAC-MANALI-CHEM01",
                name="Manali Petrochemical & Fertilizers Complex",
                sector="PETROCHEMICAL",
                state="Tamil Nadu",
                district="Chennai",
                cluster_name="Manali Coastal Petrochem Corridor",
                coordinates=[13.1650, 80.2600],
                fence_radius_m=2200.0,
                operator_name="CPCL / Manali Petrochemicals",
                erdmp_license="PESO/IND/2023/TN-MAN-0056",
                major_chemicals_stored=["Propylene Oxide", "Polyols", "Anhydrous Ammonia", "Chlorine"],
                known_flares_count=3,
                known_furnaces_count=5,
                baseline_mean_frp_mw=34.0,
                baseline_std_frp_mw=7.2,
                baseline_mean_temp_k=355.0,
                expected_diurnal_ratio=0.98,
                historical_detections_count=540,
                active_hotspots_count=1,
                current_max_frp_mw=36.2,
                current_abnormality_score=10.0,
                current_status="NOMINAL_OPERATIONS",
                last_satellite_overpass=datetime.now(timezone.utc)
            ),
            IndustrialFacility(
                id="FAC-VIZAG-STEEL01",
                name="Visakhapatnam Coastal Steel Plant (RINL)",
                sector="STEEL",
                state="Andhra Pradesh",
                district="Visakhapatnam",
                cluster_name="Gajuwaka Industrial Hub",
                coordinates=[17.6250, 83.1850],
                fence_radius_m=3800.0,
                operator_name="Rashtriya Ispat Nigam Limited",
                erdmp_license="PESO/IND/2022/AP-VIZ-0034",
                major_chemicals_stored=["Hot Metal", "Liquid Steel", "Oxygen (Cryogenic)", "Coke Oven Gas"],
                known_flares_count=3,
                known_furnaces_count=7,
                baseline_mean_frp_mw=78.0,
                baseline_std_frp_mw=15.0,
                baseline_mean_temp_k=376.0,
                expected_diurnal_ratio=0.96,
                historical_detections_count=980,
                active_hotspots_count=2,
                current_max_frp_mw=82.0,
                current_abnormality_score=12.5,
                current_status="NOMINAL_OPERATIONS",
                last_satellite_overpass=datetime.now(timezone.utc)
            ),
            IndustrialFacility(
                id="FAC-NUMALIGARH-REF01",
                name="Numaligarh Eco-Refinery Complex",
                sector="REFINERY",
                state="Assam",
                district="Golaghat",
                cluster_name="Brahmaputra Valley Energy Hub",
                coordinates=[26.5850, 93.7450],
                fence_radius_m=2500.0,
                operator_name="Numaligarh Refinery Limited",
                erdmp_license="PESO/IND/2023/AS-NUM-0001",
                major_chemicals_stored=["Motor Spirit", "High Speed Diesel", "LPG", "Wax"],
                known_flares_count=2,
                known_furnaces_count=4,
                baseline_mean_frp_mw=28.0,
                baseline_std_frp_mw=5.8,
                baseline_mean_temp_k=350.0,
                expected_diurnal_ratio=0.99,
                historical_detections_count=410,
                active_hotspots_count=1,
                current_max_frp_mw=30.5,
                current_abnormality_score=8.0,
                current_status="NOMINAL_OPERATIONS",
                last_satellite_overpass=datetime.now(timezone.utc)
            ),
            IndustrialFacility(
                id="FAC-UDAIPUR-MINE01",
                name="Debari Zinc Smelter & Chemical Complex",
                sector="MINING",
                state="Rajasthan",
                district="Udaipur",
                cluster_name="Aravalli Metallurgical Zone",
                coordinates=[24.6050, 73.8150],
                fence_radius_m=2600.0,
                operator_name="Hindustan Zinc Limited",
                erdmp_license="PESO/IND/2021/RJ-UDA-0089",
                major_chemicals_stored=["Sulfuric Acid", "Zinc Concentrate", "Lead Slag"],
                known_flares_count=1,
                known_furnaces_count=4,
                baseline_mean_frp_mw=32.0,
                baseline_std_frp_mw=6.0,
                baseline_mean_temp_k=356.0,
                expected_diurnal_ratio=0.97,
                historical_detections_count=490,
                active_hotspots_count=1,
                current_max_frp_mw=34.0,
                current_abnormality_score=9.5,
                current_status="NOMINAL_OPERATIONS",
                last_satellite_overpass=datetime.now(timezone.utc)
            ),
            IndustrialFacility(
                id="FAC-MANGALORE-CHEM01",
                name="Mangalore Coastal Chemicals & LNG Terminal",
                sector="CHEMICAL",
                state="Karnataka",
                district="Dakshina Kannada",
                cluster_name="Panambur Port Chemical Zone",
                coordinates=[12.9450, 74.8150],
                fence_radius_m=2000.0,
                operator_name="MCF / MRPL",
                erdmp_license="PESO/IND/2024/KA-MAN-0021",
                major_chemicals_stored=["Urea", "Ammonia", "Sulfuric Acid", "Phosphoric Acid"],
                known_flares_count=2,
                known_furnaces_count=3,
                baseline_mean_frp_mw=26.0,
                baseline_std_frp_mw=5.0,
                baseline_mean_temp_k=349.0,
                expected_diurnal_ratio=0.98,
                historical_detections_count=380,
                active_hotspots_count=1,
                current_max_frp_mw=27.5,
                current_abnormality_score=7.8,
                current_status="NOMINAL_OPERATIONS",
                last_satellite_overpass=datetime.now(timezone.utc)
            ),
            IndustrialFacility(
                id="FAC-PATA-PETRO01",
                name="GAIL Pata Integrated Petrochemical Complex",
                sector="PETROCHEMICAL",
                state="Uttar Pradesh",
                district="Auraiya",
                cluster_name="Northern Gas & Petrochemical Hub",
                coordinates=[26.6000, 79.5400],
                fence_radius_m=3100.0,
                operator_name="GAIL (India) Limited",
                erdmp_license="PESO/IND/2023/UP-PAT-0015",
                major_chemicals_stored=["High Density Polyethylene", "Linear Alkyl Benzene", "LPG", "Propane"],
                known_flares_count=4,
                known_furnaces_count=6,
                baseline_mean_frp_mw=48.0,
                baseline_std_frp_mw=9.0,
                baseline_mean_temp_k=360.0,
                expected_diurnal_ratio=0.97,
                historical_detections_count=690,
                active_hotspots_count=2,
                current_max_frp_mw=51.0,
                current_abnormality_score=11.0,
                current_status="NOMINAL_OPERATIONS",
                last_satellite_overpass=datetime.now(timezone.utc)
            ),
            IndustrialFacility(
                id="FAC-HALDIA-PETRO01",
                name="Haldia Petrochemicals & Refining Complex",
                sector="PETROCHEMICAL",
                state="West Bengal",
                district="Purba Medinipur",
                cluster_name="Haldia Port Industrial Belt",
                coordinates=[22.0300, 88.0800],
                fence_radius_m=3300.0,
                operator_name="Haldia Petrochemicals / IOCL",
                erdmp_license="PESO/IND/2024/WB-HAL-0008",
                major_chemicals_stored=["Naphtha", "Ethylene", "Propylene", "Butadiene", "Benzene"],
                known_flares_count=5,
                known_furnaces_count=8,
                baseline_mean_frp_mw=62.0,
                baseline_std_frp_mw=12.5,
                baseline_mean_temp_k=364.0,
                expected_diurnal_ratio=0.98,
                historical_detections_count=920,
                active_hotspots_count=2,
                current_max_frp_mw=67.0,
                current_abnormality_score=13.5,
                current_status="NOMINAL_OPERATIONS",
                last_satellite_overpass=datetime.now(timezone.utc)
            )
        ]
        for f in seeds:
            self.facilities[f.id] = f

    def haversine_distance_m(self, lat1: float, lon1: float, lat2: float, lon2: float) -> float:
        """
        Calculates great-circle distance in meters between two WGS84 coordinates.
        """
        r = 6371000.0  # Earth radius in meters
        phi1 = math.radians(lat1)
        phi2 = math.radians(lat2)
        dphi = math.radians(lat2 - lat1)
        dlambda = math.radians(lon2 - lon1)

        a = math.sin(dphi / 2.0) ** 2 + math.cos(phi1) * math.cos(phi2) * math.sin(dlambda / 2.0) ** 2
        c = 2.0 * math.atan2(math.sqrt(a), math.sqrt(1.0 - a))
        return r * c

    def attribute_thermal_event(self, lat: float, lon: float) -> Tuple[Optional[IndustrialFacility], float, bool]:
        """
        Attributes a thermal event coordinate to the closest industrial facility in the registry.
        Returns: (matched_facility, distance_meters, is_inside_fence_boundary)
        """
        best_fac = None
        min_dist = float('inf')

        for fac in self.facilities.values():
            dist = self.haversine_distance_m(lat, lon, fac.coordinates[0], fac.coordinates[1])
            if dist < min_dist:
                min_dist = dist
                best_fac = fac

        if best_fac and min_dist <= (best_fac.fence_radius_m * 2.5):
            is_inside = min_dist <= best_fac.fence_radius_m
            return best_fac, min_dist, is_inside

        return None, min_dist, False

    def get_all_facilities(self) -> List[IndustrialFacility]:
        return list(self.facilities.values())

    def get_facility_by_id(self, facility_id: str) -> Optional[IndustrialFacility]:
        return self.facilities.get(facility_id)

attribution_service = AttributionService()
